## Fancy Indexing - Integer Arrays

NumPy arrays can be indexed with slices, but also with boolean or integer arrays <b>(masks)</b>. It means passing an array of indices to access multiple array elements at once. This method is called fancy indexing. It creates copies not views.

In [3]:
os.chdir('C:\\Users\\jenny\\venvs\\py39\\Lib\\site-packages')
import numpy as np
import csv

In [4]:
a = np.arange(12)**2   

In [5]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

Suppose we want to access three different elements. We could do it like this:

In [6]:
a[2],a[6],a[8]

(4, 36, 64)

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [7]:
indx_1 = [2,6,8]

In [8]:
a[indx_1]

array([ 4, 36, 64], dtype=int32)

When using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed

In [9]:
indx_2 = np.array([[2,4],[8,10]])

In [10]:
indx_2

array([[ 2,  4],
       [ 8, 10]])

In [11]:
a[indx_2]

array([[  4,  16],
       [ 64, 100]], dtype=int32)

We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.

In [12]:
food = np.array([["blueberry","strawberry","cherry","blackberry"],
                 ["pinenut","hazelnuts","cashewnut","coconut"],
                 ["mustard","paprika","nutmeg","clove"]])

In [13]:
food

array([['blueberry', 'strawberry', 'cherry', 'blackberry'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['mustard', 'paprika', 'nutmeg', 'clove']], dtype='<U10')

##### We will now select the corner elements of this array

In [14]:
row = np.array([[0,0],[2,2]])
col = np.array([[0,3],[0,3]])

In [15]:
food[row,col]

array([['blueberry', 'blackberry'],
       ['mustard', 'clove']], dtype='<U10')

Notice that the first value in the result is food[0,0], next is food[0,3] , food[2,0] and lastly food[2,3]

In [16]:
food[2,0]

'mustard'

### Modifying Values with Fancy Indexing

Just as fancy indexing can be used to access parts of an array, it can also be used to modify parts of an array.

In [17]:
food[row,col] = "000000"

In [18]:
food

array([['000000', 'strawberry', 'cherry', '000000'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['000000', 'paprika', 'nutmeg', '000000']], dtype='<U10')

We can use any assignment-type operator for this. Consider following example:

In [19]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [20]:
indx_1

[2, 6, 8]

In [21]:
a[indx_1] = 999

In [22]:
a

array([  0,   1, 999,   9,  16,  25, 999,  49, 999,  81, 100, 121],
      dtype=int32)

In [23]:
a[indx_1] -=100

In [24]:
a

array([  0,   1, 899,   9,  16,  25, 899,  49, 899,  81, 100, 121],
      dtype=int32)